package com.riosdefuego.phonecodes

class PhonesCodes {

    private val countryCodes: HashMap<String, String> = HashMap()

    init {
        countryCodes.put("Afganistán", "+93")
        countryCodes.put("Albania", "+355")
        countryCodes.put("Alemania","+49")
        countryCodes.put("Algeria", "+213")
        countryCodes.put("Andorra", "+376")
        countryCodes.put("Angola", "+244")
        countryCodes.put("Anguila", "+1 264")
        countryCodes.put("Antártida", "+672")
        countryCodes.put("Antigua y Barbuda", "+1 268")
        countryCodes.put("Antillas Neerlandesas", "+599")
        countryCodes.put("Arabia Saudita", "+966")
        countryCodes.put("Argentina", "+54")
        countryCodes.put("Armenia", "+374")
        countryCodes.put("Aruba", "+297")
        countryCodes.put("Australia", "+61")
        countryCodes.put("Austria", "+43")
        countryCodes.put("Azerbayán", "+994")
        countryCodes.put("Bélgica", "+32")
        countryCodes.put("Bahamas", "+1 242")
        countryCodes.put("Bahrein", "+973")
        countryCodes.put("Bangladesh", "+880")
        countryCodes.put("Barbados", "+1 246")
        countryCodes.put("Belice", "+501")
        countryCodes.put("Benín", "+229")
        countryCodes.put("Bhután", "+975")
        countryCodes.put("Bielorrusia", "+375")
        countryCodes.put("Birmania", "+95")
        countryCodes.put("Bolivia", "+591")
        countryCodes.put("Bosnia y Herzegovina", "+387")
        countryCodes.put("Botswana", "+267")
        countryCodes.put("Brasil", "+55")
        countryCodes.put("Brunéi", "+673")
        countryCodes.put("Bulgaria", "+359")
        countryCodes.put("Burkina Faso", "+226")
        countryCodes.put("Burundi", "+257")
        countryCodes.put("Cabo Verde", "+238")
        countryCodes.put("Camboya", "+885")
        countryCodes.put("Camerún", "+237")
        countryCodes.put("Canadá", "+1")
        countryCodes.put("Chad", "+235")
        countryCodes.put("Chile", "+56")
        countryCodes.put("China", "+86")
        countryCodes.put("Chipre", "+357")
        countryCodes.put("Ciudad del Vaticano", "+39")
        countryCodes.put("Colombia","+57")
        countryCodes.put("Comoras", "+269")
        countryCodes.put("Congo_242", "+242")
        countryCodes.put("Congo_243", "+243")
        countryCodes.put("Corea del Norte", "+850")
        countryCodes.put("Corea del Sur", "+82")
        countryCodes.put("Costa de Marfil", "+225")
        countryCodes.put("Costa Rica", "+506")
        countryCodes.put("Croacia", "+385")
        countryCodes.put("Cuba", "+53")
        countryCodes.put("Dinamarca", "+45")
        countryCodes.put("Dominica", "+1 767")
        countryCodes.put("Ecuador", "+593")
        countryCodes.put("Egipto", "+20")
        countryCodes.put("El Salvador", "+503")
        countryCodes.put("Emiratos Árabes Unidos", "+971")
        countryCodes.put("Eritrea", "+291")
        countryCodes.put("Eslovaquia", "+421")
        countryCodes.put("Eslovenia", "+386")
        countryCodes.put("España", "+34")
        countryCodes.put("Estados Unidos de América", "+1")
        countryCodes.put("Estonia", "+372")
        countryCodes.put("Etiopía", "+251")
        countryCodes.put("Filipinas", "+63")
        countryCodes.put("Finlandia", "+358")
        countryCodes.put("Fiyi", "+679")
        countryCodes.put("Francia", "+33")
        countryCodes.put("Gabón", "+241")
        countryCodes.put("Gambia", "+220")
        countryCodes.put("Georgia", "+995")
        countryCodes.put("Ghana", "+233")
        countryCodes.put("Gibraltar", "+350")
        countryCodes.put("Granada", "+1 473")
        countryCodes.put("Grecia", "+30")
        countryCodes.put("Groenlandia", "+299")
        countryCodes.put("Guam", "+1 671")
        countryCodes.put("Guatemala", "+502")
        countryCodes.put("Guinea", "+224")
        countryCodes.put("Guinea Ecuatorial", "+240")
        countryCodes.put("Guinea-Bissau", "+245")
        countryCodes.put("Guyana", "+592")
        countryCodes.put("Haití", "+509")
        countryCodes.put("Honduras", "+504")
        countryCodes.put("Hong kong", "+852")
        countryCodes.put("Hungría", "+36")
        countryCodes.put("India", "+91")
        countryCodes.put("Indonesia", "+62")
        countryCodes.put("Irán", "+98")
        countryCodes.put("Irak", "+964")
        countryCodes.put("Irlanda", "+353")
        countryCodes.put("Isla de Man", "+44")
        countryCodes.put("Isla de Navidad", "+61")
        countryCodes.put("Islandia", "+354")
        countryCodes.put("Islas Bermudas", "+1 441")
        countryCodes.put("Islas Caimán", "+1 345")
        countryCodes.put("Islas Cocos (Keeling)", "+61")
        countryCodes.put("Islas Cook", "+682")
        countryCodes.put("Islas Feroe", "+298")
        countryCodes.put("Islas Maldivas", "+960")
        countryCodes.put("Islas Malvinas", "+500")
        countryCodes.put("Islas Marianas del Norte", "+1 670")
        countryCodes.put("Islas Marshall", "+692")
        countryCodes.put("Islas Pitcairn", "+870")
        countryCodes.put("Islas Salomón", "+677")
        countryCodes.put("Islas Turcas y Caicos", "+1 649")
        countryCodes.put("Islas Vírgenes Británicas", "+1 284")
        countryCodes.put("Islas Vírgenes de los Estados Unidos", "+1 340")
        countryCodes.put("Israel", "+972")
        countryCodes.put("Italia", "+39")
        countryCodes.put("Jamaica", "+1 876")
        countryCodes.put("Japón", "+81")
        countryCodes.put("Jordania", "+962")
        countryCodes.put("Kazajistán", "+7")
        countryCodes.put("Kenia", "+254")
        countryCodes.put("Kirgizstán", "+996")
        countryCodes.put("Kiribati", "+686")
        countryCodes.put("Kuwait", "+965")
        countryCodes.put("Líbano", "+961")
        countryCodes.put("Laos", "+856")
        countryCodes.put("Lesoto", "+266")
        countryCodes.put("Letonia", "+371")
        countryCodes.put("Liberia", "+231")
        countryCodes.put("Libia", "+218")
        countryCodes.put("Liechtenstein", "+423")
        countryCodes.put("Lituania", "+370")
        countryCodes.put("Luxemburgo", "+352")
        countryCodes.put("México", "+52")
        countryCodes.put("Mónaco", "+377")
        countryCodes.put("Macao", "+853")
        countryCodes.put("Macedônia", "+389")
        countryCodes.put("Madagascar", "+261")
        countryCodes.put("Malasia", "+60")
        countryCodes.put("Malawi", "+265")
        countryCodes.put("Mali", "+223")
        countryCodes.put("Malta", "+356")
        countryCodes.put("Marruecos", "+212")
        countryCodes.put("Mauricio", "+230")
        countryCodes.put("Mauritania", "+222")
        countryCodes.put("Mayotte","+262")
        countryCodes.put("Micronesia", "+691")
        countryCodes.put("Moldavia", "+373")
        countryCodes.put("Mongolia", "+976")
        countryCodes.put("Montenegro", "+382")
        countryCodes.put("Montserrat", "+1 664")
        countryCodes.put("Mozambique", "+258")
        countryCodes.put("Namibia", "+264")
        countryCodes.put("Nauru", "+674")
        countryCodes.put("Nepal", "+977")
        countryCodes.put("Nicaragua", "+505")
        countryCodes.put("Niger", "+227")
        countryCodes.put("Nigeria", "+234")
        countryCodes.put("Niue", "+683")
        countryCodes.put("Noruega", "+47")
        countryCodes.put("Nueva Caledonia", "+687")
        countryCodes.put("Nueva Zelanda","+64")
        countryCodes.put("Omán", "+968")
        countryCodes.put("Países Bajos", "+31")
        countryCodes.put("Pakistán", "+92")
        countryCodes.put("Palau", "+680")
        countryCodes.put("Panamá", "+507")
        countryCodes.put("Papúa Nueva Guinea", "+675")
        countryCodes.put("Paraguay", "+595")
        countryCodes.put("Perú", "+51")
        countryCodes.put("Polinesia Francesa", "+689")
        countryCodes.put("Polonia", "+48")
        countryCodes.put("Portugal", "+351")
        countryCodes.put("Puerto Rico", "+1")
        countryCodes.put("Qatar", "+974")
        countryCodes.put("Reino Unido", "+44")
        countryCodes.put("República Centroafricana", "+236")
        countryCodes.put("República Checa", "+420")
        countryCodes.put("República Dominicana", "+1 809")
        countryCodes.put("Ruanda", "+250")
        countryCodes.put("Rumanía", "+40")
        countryCodes.put("Rusia", "+7")
        countryCodes.put("Samoa", "+685")
        countryCodes.put("Samoa Americana", "+1 684")
        countryCodes.put("San Bartolomé", "+590")
        countryCodes.put("San Cristóbal y Nieves", "+1 869")
        countryCodes.put("San Marino", "+378")
        countryCodes.put("San Martín (Francia)", "+1 599")
        countryCodes.put("San Pedro y Miquelón", "+508")
        countryCodes.put("San Vicente y las Granadinas", "+1 784")
        countryCodes.put("Santa Elena", "+290")
        countryCodes.put("Santa Lucía", "+1 758")
        countryCodes.put("Santo Tomé y Príncipe", "+239")
        countryCodes.put("Senegal", "+221")
        countryCodes.put("Serbia", "+381")
        countryCodes.put("Seychelles", "+248")
        countryCodes.put("Sierra Leona", "+232")
        countryCodes.put("Singapur", "+65")
        countryCodes.put("Siria", "+963")
        countryCodes.put("Somalia", "+252")
        countryCodes.put("Sri lanka", "+94")
        countryCodes.put("Sudáfrica", "+27")
        countryCodes.put("Sudán", "+249")
        countryCodes.put("Suecia", "+46")
        countryCodes.put("Suiza", "+41")
        countryCodes.put("Surinám", "+597")
        countryCodes.put("Swazilandia", "+268")
        countryCodes.put("Tadjikistán", "+992")
        countryCodes.put("Tailandia", "+66")
        countryCodes.put("Taiwán", "+886")
        countryCodes.put("Tanzania", "+255")
        countryCodes.put("Timor Oriental", "+670")
        countryCodes.put("Togo", "+228")
        countryCodes.put("Tokelau", "+690")
        countryCodes.put("Tonga", "+676")
        countryCodes.put("Trinidad y Tobago", "+1 868")
        countryCodes.put("Tunez", "+216")
        countryCodes.put("Turkmenistán", "+993")
        countryCodes.put("Turquía", "+90")
        countryCodes.put("Tuvalu", "+688")
        countryCodes.put("Ucrania", "+380")
        countryCodes.put("Uganda", "+256")
        countryCodes.put("Uruguay", "+598")
        countryCodes.put("Uzbekistán", "+998")
        countryCodes.put("Vanuatu", "+678")
        countryCodes.put("Venezuela", "+58")
        countryCodes.put("Vietnam", "+84")
        countryCodes.put("Wallis y Futuna", "+681")
        countryCodes.put("Yemen", "+967")
        countryCodes.put("Yibuti", "+253")
        countryCodes.put("Zambia", "+260")
        countryCodes.put("Zimbabue", "+263")
    }

    fun getMapOfCountryNamesAndCodes(): HashMap<String, String> {
        return countryCodes
    }

    fun getListOfCountries(): List<String>{
        val namesList = countryCodes.keys
        return namesList.toList().sorted()
    }

    fun getCodeList(): List<String>{
        val codesList = countryCodes.values
        return codesList.toList()
    }

    fun getCodeTroughCountryName(countryName: String): String{
        return countryCodes.getValue(countryName).toString()
    }

}